# Generated by Django 5.2.4 on 2025-12-09 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated_at'),
        ),
        migrations.AlterModelTable(
            name='favorite',
            table=None,
        ),
    ]
