# Generated by Django 5.2.4 on 2025-12-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='favorite',
            name='snapshot_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
