# Generated by Codex on 2026-06-08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("favorites", "0002_favorite_snapshot_favorite_snapshot_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestFavorite",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name="Id")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated_at")),
                ("guest_phone", models.CharField(max_length=20)),
                ("object_id", models.CharField(max_length=255)),
                ("snapshot", models.JSONField(blank=True, default=dict, null=True)),
                ("snapshot_at", models.DateTimeField(blank=True, null=True)),
                ("content_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype")),
                ("linked_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="linked_guest_favorites", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Guest Favorite",
                "verbose_name_plural": "Guest Favorites",
                "unique_together": {("guest_phone", "content_type", "object_id")},
            },
        ),
    ]
