# Generated by Django 5.2.4 on 2025-09-01 13:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(help_text='Name of the amenity or feature.', max_length=255, verbose_name='Amenity Name')),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'db_table': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('image', models.ImageField(help_text='Upload an image for the listing.', upload_to='listing_images/', verbose_name='Image File')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for the image.', max_length=255, verbose_name='Alt Text')),
                ('is_primary', models.BooleanField(default=False, help_text='Marks the main image for the listing.', verbose_name='Primary Image')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Listing Image',
                'verbose_name_plural': 'Listing Images',
                'db_table': 'listing_images',
            },
        ),
        migrations.CreateModel(
            name='HotelListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('title', models.CharField(help_text="Title of the listing, e.g., 'Luxury Suite with Pool View'.", max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the listing.', verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, null=True, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the listing is active and visible.', verbose_name='Is Active')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Number of guests this service can accommodate.', null=True, verbose_name='Capacity')),
                ('service_type', models.CharField(choices=[('room', 'Room'), ('auditorium', 'Auditorium'), ('conference_hall', 'Conference Hall')], max_length=50, verbose_name='Service Type')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='core.address')),
                ('amenities', models.ManyToManyField(blank=True, related_name='hotel_listings', to='listing.amenity', verbose_name='Amenities')),
                ('company', models.ForeignKey(blank=True, help_text='The company that owns this listing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='account.companyprofile', verbose_name='Company')),
                ('images', models.ManyToManyField(to='listing.listingimage')),
            ],
            options={
                'verbose_name': 'Hotel Listing',
                'verbose_name_plural': 'Hotel Listings',
                'db_table': 'hotel_listings',
            },
        ),
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('title', models.CharField(help_text="Title of the listing, e.g., 'Luxury Suite with Pool View'.", max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the listing.', verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, null=True, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the listing is active and visible.', verbose_name='Is Active')),
                ('brand', models.CharField(choices=[('toyota', 'Toyota'), ('bmw', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('honda', 'Honda'), ('ford', 'Ford'), ('nissan', 'Nissan'), ('chevrolet', 'Chevrolet'), ('kia', 'Kia'), ('hyundai', 'Hyundai'), ('volvo', 'Volvo'), ('jeep', 'Jeep'), ('porsche', 'Porsche'), ('lexus', 'Lexus'), ('mazda', 'Mazda'), ('land_rover', 'Land Rover'), ('subaru', 'Subaru'), ('fiat', 'Fiat'), ('peugeot', 'Peugeot')], help_text='Car brand, e.g., Toyota, BMW.', max_length=100, verbose_name='Brand')),
                ('model', models.CharField(help_text='Car model, e.g., Camry, X5.', max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(help_text='Manufacturing year of the car.', verbose_name='Year')),
                ('mileage', models.PositiveIntegerField(help_text='Mileage of the car in kilometers.', verbose_name='Mileage (km)')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('electric', 'Electric'), ('petrol', 'Petrol'), ('hybrid', 'Hybrid')], max_length=50, verbose_name='Engine Type')),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=50, verbose_name='Transmission')),
                ('is_for_sale', models.BooleanField(default=False, verbose_name='Is for Sale')),
                ('company', models.ForeignKey(blank=True, help_text='The company that owns this listing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='account.companyprofile', verbose_name='Company')),
                ('individual_owner', models.ForeignKey(blank=True, help_text='The individual person that owns this listing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='account.individualownerprofile', verbose_name='Individual Owner')),
                ('images', models.ManyToManyField(to='listing.listingimage')),
            ],
            options={
                'verbose_name': 'Car Listing',
                'verbose_name_plural': 'Car Listings',
                'db_table': 'car_listings',
            },
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('title', models.CharField(help_text="Title of the listing, e.g., 'Luxury Suite with Pool View'.", max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the listing.', verbose_name='Description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, null=True, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the listing is active and visible.', verbose_name='Is Active')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('condo', 'Condo'), ('villa', 'Villa'), ('house', 'House'), ('land', 'Land')], max_length=50, verbose_name='Property Type')),
                ('bedrooms', models.PositiveIntegerField(verbose_name='Bedrooms')),
                ('bathrooms', models.PositiveIntegerField(verbose_name='Bathrooms')),
                ('square_meters', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Square Meters')),
                ('is_furnished', models.BooleanField(default=False, verbose_name='Is Furnished')),
                ('is_for_sale', models.BooleanField(default=False, verbose_name='Is for Sale')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='core.address')),
                ('company', models.ForeignKey(blank=True, help_text='The company that owns this listing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='account.companyprofile', verbose_name='Company')),
                ('images', models.ManyToManyField(to='listing.listingimage')),
                ('individual_owner', models.ForeignKey(blank=True, help_text='The individual person that owns this listing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='account.individualownerprofile', verbose_name='Individual Owner')),
            ],
            options={
                'verbose_name': 'Property Listing',
                'verbose_name_plural': 'Property Listings',
                'db_table': 'property_listings',
            },
        ),
    ]
