# Generated by Django 5.2.4 on 2025-09-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='is_for_sale',
        ),
        migrations.AddField(
            model_name='carlisting',
            name='car_class',
            field=models.CharField(choices=[('luxury', 'Luxury'), ('normal', 'Normal')], default='normal', max_length=200, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='rent', help_text='Whether the item is For sell or Rent.', max_length=200, verbose_name='Listing Type'),
        ),
    ]
