# Generated by Django 5.2.4 on 2025-12-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_companyprofile_approved_at_and_more'),
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stayavailability',
            name='hotel_date_idx',
        ),
        migrations.AddIndex(
            model_name='stayavailability',
            index=models.Index(fields=['hotel', 'room', 'date'], name='listing_sta_hotel_i_ed8e04_idx'),
        ),
        migrations.AddConstraint(
            model_name='stayavailability',
            constraint=models.UniqueConstraint(fields=('date', 'hotel', 'room'), name='hotel_date_room_idx'),
        ),
    ]
