# Generated by Django 5.2.4 on 2025-09-05 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_exactly_one_target',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_valid_dates',
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='eventspacelisting',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Price of the service/product (if applicable).', max_digits=10, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('room__isnull', False), ('event_space__isnull', True)), models.Q(('room__isnull', True), ('event_space__isnull', False)), _connector='OR'), name='booking_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('check_in_date__lt', models.F('check_out_date'))), name='booking_valid_dates'),
        ),
    ]
