# Generated by Django 5.2.4 on 2025-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='car_class',
            field=models.CharField(choices=[('luxury', 'Luxury'), ('normal', 'Normal')], default='normal', max_length=200, verbose_name='Class Category'),
        ),
    ]
