# Generated by Django 5.2.4 on 2025-11-19 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_stayavailability_options_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='listing.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
