# Generated by Django 5.2.4 on 2025-10-20 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('listing', '0002_alter_roomlisting_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlisting',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='core.address'),
        ),
    ]
