# Generated by Django 5.2.4 on 2025-10-13 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_carlisting_car_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlisting',
            name='images',
        ),
        migrations.RemoveField(
            model_name='eventspacelisting',
            name='images',
        ),
        migrations.RemoveField(
            model_name='guesthouselisting',
            name='images',
        ),
        migrations.RemoveField(
            model_name='propertylisting',
            name='images',
        ),
        migrations.RemoveField(
            model_name='roomlisting',
            name='images',
        ),
    ]
