# Generated by Django 5.2.4 on 2025-12-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_remove_stayavailability_hotel_date_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
