# Generated by Django 5.2.4 on 2025-11-24 09:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_bookingrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='car_class',
            field=models.CharField(choices=[('luxury', 'Luxury'), ('normal', 'Normal')], default='normal', max_length=200, verbose_name='Class Category'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='rent', help_text='Whether the item is For sell or Rent.', max_length=200, verbose_name='Listing Type'),
        ),
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('start_date', models.DateField(verbose_name='Rental Start Date')),
                ('end_date', models.DateField(verbose_name='Rental End Date')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Rental Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Rental',
                'verbose_name_plural': 'Car Rentals',
            },
        ),
        migrations.CreateModel(
            name='CarRentalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('units_rent', models.PositiveIntegerField(default=1, help_text='Number of cars being rented.', verbose_name='Quantity')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_items', to='listing.carlisting', verbose_name='Car Listing')),
                ('car_rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_items', to='listing.carrental', verbose_name='Car Rental')),
            ],
            options={
                'verbose_name': 'Car Rental Item',
                'verbose_name_plural': 'Car Rental Items',
            },
        ),
        migrations.CreateModel(
            name='CarSale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('sale_date', models.DateField(auto_now_add=True, verbose_name='Sale Date')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Sale Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Car Sale',
                'verbose_name_plural': 'Car Sales',
            },
        ),
        migrations.CreateModel(
            name='CarSaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('units_sale', models.PositiveIntegerField(default=1, help_text='Number of cars being sold.', verbose_name='Quantity')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='listing.carlisting', verbose_name='Car Listing')),
                ('car_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='listing.carsale', verbose_name='Car Sale')),
            ],
            options={
                'verbose_name': 'Car Sale Item',
                'verbose_name_plural': 'Car Sale Items',
            },
        ),
    ]
