# Generated by Django 5.2.4 on 2025-12-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_booking_snapshot_bookingitem_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='currency',
            field=models.CharField(default='ETB', help_text="ISO 4217 currency code for the price fields, e.g., 'ETB'.", max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='currency',
            field=models.CharField(default='ETB', max_length=3),
        ),
        migrations.AddField(
            model_name='eventspacelisting',
            name='currency',
            field=models.CharField(default='ETB', help_text="ISO 4217 currency code for the price fields, e.g., 'ETB'.", max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='guesthouselisting',
            name='currency',
            field=models.CharField(default='ETB', help_text="ISO 4217 currency code for the price fields, e.g., 'ETB'.", max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='currency',
            field=models.CharField(default='ETB', help_text="ISO 4217 currency code for the price fields, e.g., 'ETB'.", max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='currency',
            field=models.CharField(default='ETB', help_text="ISO 4217 currency code for the price fields, e.g., 'ETB'.", max_length=3, verbose_name='Currency'),
        ),
    ]
