# Generated by Django 5.2.4 on 2025-10-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_alter_roomlisting_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carlisting',
            name='car_class',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='propertylisting',
            name='listing_type',
        ),
    ]
