# Generated by Django 5.2.4 on 2025-11-26 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_carlisting_car_class_carlisting_listing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsaleitem',
            name='car_sale',
        ),
        migrations.RemoveField(
            model_name='carsaleitem',
            name='car_listing',
        ),
        migrations.AddField(
            model_name='carlisting',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='CarAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('availability_type', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='rent', max_length=20, verbose_name='Availability Type')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the car is currently available for booking/purchase', verbose_name='Is Available')),
                ('available_from', models.DateTimeField(blank=True, help_text='Date from which the car is available (for rentals)', null=True, verbose_name='Available From')),
                ('available_to', models.DateTimeField(blank=True, help_text='Date until which the car is available (for rentals)', null=True, verbose_name='Available To')),
                ('quantity_available', models.PositiveIntegerField(default=1, help_text='Number of units available for sale/rent', verbose_name='Quantity Available')),
                ('car_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='listing.carlisting', verbose_name='Car Listing')),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availabilities',
                'db_table': 'availabilities',
            },
        ),
        migrations.DeleteModel(
            name='CarSale',
        ),
        migrations.DeleteModel(
            name='CarSaleItem',
        ),
        migrations.AddIndex(
            model_name='caravailability',
            index=models.Index(fields=['car_listing', 'availability_type', 'is_available'], name='availabilit_car_lis_08b44f_idx'),
        ),
        migrations.AddIndex(
            model_name='caravailability',
            index=models.Index(fields=['available_from', 'available_to'], name='availabilit_availab_1b3157_idx'),
        ),
    ]
