# Generated by Django 5.2.4 on 2025-11-25 11:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_hotelprofile_featured'),
        ('listing', '0004_carlisting_car_class_carlisting_listing_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('recurring', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'seasons',
            },
        ),
        migrations.CreateModel(
            name='BookingItemPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('date', models.DateField(db_index=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.PositiveIntegerField(default=1)),
                ('booking_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='listing.bookingitem')),
            ],
            options={
                'db_table': 'booking_item_prices',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SeasonalRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('min_stay', models.PositiveIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.companyprofile')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.hotelprofile')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listing.roomlisting')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='listing.season')),
            ],
            options={
                'db_table': 'seasonal_rates',
            },
        ),
    ]
