# Generated by Django 5.2.4 on 2025-12-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_carlisting_currency_carrental_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='ETB', help_text="ISO 4217 currency code for the price fields, e.g., 'ETB'.", max_length=3, verbose_name='Currency'),
        ),
    ]
