# Generated by Django 5.2.4 on 2025-11-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_remove_carsaleitem_car_sale_and_more'),
        ('listing', '0005_season_bookingitemprice_seasonalrate'),
    ]

    operations = [
    ]
