# Generated by Django 5.2.4 on 2025-12-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_booking_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspacebooking',
            name='currency',
            field=models.CharField(default='ETB', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='guesthousebooking',
            name='currency',
            field=models.CharField(default='ETB', max_length=3),
        ),
    ]
