# Generated by Django 5.2.4 on 2025-11-28 06:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_hotelprofile_featured'),
        ('core', '0001_initial'),
        ('listing', '0006_merge_20251127_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSpaceListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('title', models.CharField(help_text="Title of the listing, e.g., 'Luxury Suite with Pool View'.", max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the listing.', verbose_name='Description')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, verbose_name='Price')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the listing is active and visible.', verbose_name='Is Active')),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('space_type', models.CharField(choices=[('auditorium', 'Auditorium'), ('conference_hall', 'Conference Hall'), ('meeting_room', 'Meeting Room')], max_length=50)),
                ('floor_area_sqm', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='core.address')),
                ('amenities', models.ManyToManyField(blank=True, related_name='event_space_listings', to='listing.amenity', verbose_name='Amenities')),
                ('hotel', models.ForeignKey(blank=True, help_text='The company that owns this listing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_space_listings', to='account.hotelprofile', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Event space',
                'verbose_name_plural': 'Event Spaces',
                'db_table': 'event_spaces',
            },
        ),
        migrations.CreateModel(
            name='EventSpaceAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('date', models.DateField(db_index=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('space_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='listing.eventspacelisting')),
            ],
            options={
                'verbose_name': 'Event space Availability',
                'verbose_name_plural': 'Event Space Availabilities',
                'db_table': 'event_space_availabilities',
                'ordering': ['date'],
                'unique_together': {('space_listing', 'date')},
            },
        ),
    ]
