# Generated by Django 5.2.4 on 2025-12-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_companyprofile_approved_at_and_more'),
        ('listing', '0006_eventspacebooking_currency_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stayavailability',
            constraint=models.CheckConstraint(condition=models.Q(('available_rooms__gte', 0)), name='stay_availability_non_negative'),
        ),
    ]
