# Generated by Django 5.2.4 on 2026-01-04 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('listing', '0007_stayavailability_stay_availability_non_negative'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Whether the user confirmed they read and accepted the T&C', verbose_name='Terms Accepted'),
        ),
        migrations.AddField(
            model_name='booking',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user accepted T&C', null=True, verbose_name='Terms Accepted At'),
        ),
        migrations.AddField(
            model_name='booking',
            name='terms_content_ref',
            field=models.TextField(blank=True, help_text='Full T&C content at time of booking (for legal record)', null=True, verbose_name='T&C Content Snapshot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='terms_version',
            field=models.CharField(blank=True, help_text='Version of T&C that user accepted', max_length=50, verbose_name='T&C Version'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Whether the user confirmed they read and accepted the T&C', verbose_name='Terms Accepted'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user accepted T&C', null=True, verbose_name='Terms Accepted At'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='terms_content_snapshot',
            field=models.TextField(blank=True, help_text='Full T&C content at time of booking (for legal record)', null=True, verbose_name='T&C Content Snapshot'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='terms_version',
            field=models.CharField(blank=True, help_text='Version of T&C that user accepted', max_length=50, verbose_name='T&C Version'),
        ),
        migrations.AddField(
            model_name='eventspacebooking',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Whether the user confirmed they read and accepted the T&C', verbose_name='Terms Accepted'),
        ),
        migrations.AddField(
            model_name='eventspacebooking',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user accepted T&C', null=True, verbose_name='Terms Accepted At'),
        ),
        migrations.AddField(
            model_name='eventspacebooking',
            name='terms_content_snapshot',
            field=models.TextField(blank=True, help_text='Full T&C content at time of booking (for legal record)', null=True, verbose_name='T&C Content Snapshot'),
        ),
        migrations.AddField(
            model_name='eventspacebooking',
            name='terms_version',
            field=models.CharField(blank=True, help_text='Version of T&C that user accepted', max_length=50, verbose_name='T&C Version'),
        ),
        migrations.AddField(
            model_name='guesthousebooking',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Whether the user confirmed they read and accepted the T&C', verbose_name='Terms Accepted'),
        ),
        migrations.AddField(
            model_name='guesthousebooking',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user accepted T&C', null=True, verbose_name='Terms Accepted At'),
        ),
        migrations.AddField(
            model_name='guesthousebooking',
            name='terms_content_snapshot',
            field=models.TextField(blank=True, help_text='Full T&C content at time of booking (for legal record)', null=True, verbose_name='T&C Content Snapshot'),
        ),
        migrations.AddField(
            model_name='guesthousebooking',
            name='terms_version',
            field=models.CharField(blank=True, help_text='Version of T&C that user accepted', max_length=50, verbose_name='T&C Version'),
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('object_id', models.UUIDField(help_text='ID of the specific hotel/space/guesthouse', verbose_name='Object ID')),
                ('version', models.CharField(help_text="Version identifier (e.g., '1.0', '2024-Q1', 'v2.5')", max_length=50, verbose_name='Version')),
                ('title', models.CharField(default='Terms and Conditions', help_text='Title of the terms document', max_length=255, verbose_name='Title')),
                ('content', models.TextField(help_text='Full T&C text in HTML or Markdown format', verbose_name='Content')),
                ('effective_date', models.DateField(help_text='Date when this version becomes active', verbose_name='Effective Date')),
                ('is_active', models.BooleanField(default=True, help_text='Only one version should be active at a time per object', verbose_name='Is Active')),
                ('content_type', models.ForeignKey(help_text='Type of object these terms apply to (Hotel, EventSpace, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Terms and Conditions',
                'verbose_name_plural': 'Terms and Conditions',
                'db_table': 'terms_and_conditions',
                'ordering': ['-effective_date', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'is_active'], name='terms_and_c_content_adbdb0_idx'), models.Index(fields=['effective_date'], name='terms_and_c_effecti_e2256a_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'version'), name='unique_tc_version_per_object')],
            },
        ),
    ]
