# Generated by Django 5.2.4 on 2025-12-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_eventspacelisting_eventspaceavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspacelisting',
            name='total_units',
            field=models.PositiveIntegerField(default=1, help_text='How many eventspace of this type exist in the property.', verbose_name='Total eventspace of This Type'),
        ),
    ]
