# Generated by Django 5.2.4 on 2026-01-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_add_terms_and_conditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='terms_content_ref',
            new_name='terms_content_snapshot',
        ),
    ]
