# Generated by Django 5.2.4 on 2025-12-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_eventspacelisting_total_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspaceavailability',
            name='available_eventspace',
            field=models.PositiveIntegerField(default=0, verbose_name='Available Event Spaces'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('walk_in', 'Walk-In')], default='pending', max_length=20),
        ),
    ]
