# Generated by Django 5.2.4 on 2025-12-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_eventspacelisting_total_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('walk_in', 'Walk-In')], default='pending', max_length=20),
        ),
    ]
