# Generated by Django 5.2.4 on 2025-12-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_eventspaceavailability_available_eventspace_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caravailability',
            options={'verbose_name': 'Car Availability', 'verbose_name_plural': 'Car Availabilities'},
        ),
        migrations.AlterModelOptions(
            name='roomlisting',
            options={'verbose_name': 'Room Listing', 'verbose_name_plural': 'Room Listing'},
        ),
        migrations.RenameIndex(
            model_name='caravailability',
            new_name='Car availab_car_lis_157d59_idx',
            old_name='availabilit_car_lis_08b44f_idx',
        ),
        migrations.RenameIndex(
            model_name='caravailability',
            new_name='Car availab_availab_970568_idx',
            old_name='availabilit_availab_1b3157_idx',
        ),
        migrations.AddField(
            model_name='carlisting',
            name='seats',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterModelTable(
            name='caravailability',
            table='Car availabilities',
        ),
    ]
