# Generated by Django 5.2.4 on 2026-01-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_companyprofile_chapa_subaccount_id_and_more'),
        ('core', '0002_alter_currencyrate_date'),
        ('listing', '0009_rename_terms_content_ref_booking_terms_content_snapshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomlisting',
            options={'verbose_name': 'Room Listing', 'verbose_name_plural': 'Room Listings'},
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='address',
            field=models.ForeignKey(help_text='Branch address for this room type. Must correspond to a hotel branch location.', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='core.address'),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='hotel',
            field=models.ForeignKey(help_text='The hotel that owns this room type.', on_delete=django.db.models.deletion.CASCADE, related_name='room_listings', to='account.hotelprofile', verbose_name='Hotel'),
        ),
        migrations.AddConstraint(
            model_name='roomlisting',
            constraint=models.CheckConstraint(condition=models.Q(('hotel__isnull', False)), name='room_must_have_hotel'),
        ),
    ]
