# Generated by Django 5.2.4 on 2025-12-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_alter_booking_status'),
        ('listing', '0010_alter_caravailability_options_and_more'),
    ]

    operations = [
    ]
