# Generated by Django 5.2.4 on 2026-01-07 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_companyprofile_address_and_more'),
        ('core', '0003_alter_address_country'),
        ('listing', '0010_enforce_hotel_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspacelisting',
            name='address',
            field=models.OneToOneField(help_text='Event space location address', on_delete=django.db.models.deletion.RESTRICT, related_name='event_space_listing', to='core.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='eventspacelisting',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='The hotel that owns this event space.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_space_listings', to='account.hotelprofile', verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='guesthouselisting',
            name='address',
            field=models.OneToOneField(help_text='Guesthouse location address', on_delete=django.db.models.deletion.RESTRICT, related_name='guesthouse_listing', to='core.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='address',
            field=models.OneToOneField(help_text='Property location address', on_delete=django.db.models.deletion.RESTRICT, related_name='property_listing', to='core.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='address',
            field=models.ForeignKey(help_text='Branch address for this room type. Must correspond to a hotel branch location.', on_delete=django.db.models.deletion.RESTRICT, related_name='room_listings', to='core.address', verbose_name='Address'),
        ),
    ]
