# Generated by Django 5.2.4 on 2025-12-10 08:40

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_alter_caravailability_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSpaceBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('check_in_date', models.DateField(verbose_name='Check-In Date')),
                ('check_out_date', models.DateField(verbose_name='Check-Out Date')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('walk_in', 'Walk-In')], default='pending', max_length=20, verbose_name='Status')),
                ('event_type', models.CharField(choices=[('walk_in', 'Walk-In'), ('meeting', 'Meeting'), ('conference', 'Conference'), ('seminar', 'Seminar'), ('workshop', 'Workshop'), ('webinar', 'Webinar'), ('networking', 'Networking'), ('trade_show', 'Trade Show'), ('social', 'Social Event'), ('fundraiser', 'Fundraiser'), ('retreat', 'Retreat')], default='meeting', max_length=20)),
            ],
            options={
                'verbose_name': 'Event Space Booking',
                'verbose_name_plural': 'Event Space Bookings',
                'db_table': 'event_space_bookings',
            },
        ),
        migrations.CreateModel(
            name='EventSpaceBookingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('units_booked', models.PositiveIntegerField(default=1)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Event Space Booking Item',
                'verbose_name_plural': 'Event Space Booking Items',
                'db_table': 'event_space_booking_items',
            },
        ),
        migrations.RemoveIndex(
            model_name='caravailability',
            name='Car availab_car_lis_157d59_idx',
        ),
        migrations.RemoveIndex(
            model_name='caravailability',
            name='Car availab_availab_970568_idx',
        ),
        migrations.RemoveField(
            model_name='caravailability',
            name='availability_type',
        ),
        migrations.RemoveField(
            model_name='caravailability',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='caravailability',
            name='available_to',
        ),
        migrations.RemoveField(
            model_name='caravailability',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='caravailability',
            name='quantity_available',
        ),
        migrations.AddField(
            model_name='caravailability',
            name='available_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='caravailability',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 12, 10, 8, 40, 43, 524688, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='caravailability',
            name='car_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_availabilities', to='listing.carlisting'),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='seats',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddIndex(
            model_name='caravailability',
            index=models.Index(fields=['car_listing', 'date'], name='listing_car_car_lis_59da60_idx'),
        ),
        migrations.AddConstraint(
            model_name='caravailability',
            constraint=models.UniqueConstraint(fields=('car_listing', 'date'), name='car_listing_date_unique'),
        ),
        migrations.AlterModelTable(
            name='caravailability',
            table=None,
        ),
        migrations.AddField(
            model_name='eventspacebooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='eventspacebookingitem',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='listing.eventspacebooking', verbose_name='Booking'),
        ),
        migrations.AddField(
            model_name='eventspacebookingitem',
            name='event_space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_space_booking_items', to='listing.eventspacelisting', verbose_name='Event Space'),
        ),
    ]
