# Generated by Django 5.2.4 on 2026-01-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_companyprofile_address_and_more'),
        ('listing', '0011_alter_eventspacelisting_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspacelisting',
            name='hotel',
            field=models.ForeignKey(help_text='The hotel that owns this event space.', on_delete=django.db.models.deletion.CASCADE, related_name='event_space_listings', to='account.hotelprofile', verbose_name='Hotel'),
        ),
    ]
