# Generated by Django 5.2.4 on 2025-12-11 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_eventspacebooking_eventspacebookingitem_and_more'),
        ('listing', '0012_alter_carlisting_seats_eventspacebooking_and_more'),
    ]

    operations = [
    ]
