# Generated by Django 5.2.4 on 2025-12-11 08:35

import apps.listing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_alter_carlisting_seats_eventspacebooking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonalrate',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, validators=[apps.listing.models.validate_days_of_week]),
        ),
    ]
