# Generated by Django 5.2.4 on 2025-12-11 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('listing', '0013_merge_20251211_1416'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouselisting',
            name='facility',
            field=models.ManyToManyField(blank=True, related_name='guest_house_listing', to='core.facility', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='caravailability',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='GuestHouseBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('walk_in', 'Walk-In')], default='pending', max_length=20)),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuestHouseBookingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('units_booked', models.PositiveIntegerField(default=1)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='listing.guesthousebooking', verbose_name='Booking')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_items', to='listing.guesthouselisting', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Booking Item',
                'verbose_name_plural': 'Booking Items',
                'db_table': 'guestbooking_items',
            },
        ),
        migrations.CreateModel(
            name='GuestHouseAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('date', models.DateField()),
                ('available_rooms', models.PositiveIntegerField()),
                ('guest_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='listing.guesthouselisting')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('guest_house', 'date')},
            },
        ),
    ]
