# Generated by Django 5.2.4 on 2026-01-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_companyprofile_address_and_more'),
        ('core', '0003_alter_address_country'),
        ('listing', '0013_create_guesthouse_structure'),
    ]

    operations = [
        # Phase 1: Restore missing columns and M2M tables in database (Database only)
        # This ensures the physical DB matches what 0013 expects and 0014 will alter.
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    -- Ensure columns exist in guest_houses
                    ALTER TABLE guest_houses ADD COLUMN IF NOT EXISTS address_id uuid REFERENCES addresses(id) ON DELETE RESTRICT;
                    ALTER TABLE guest_houses ADD COLUMN IF NOT EXISTS company_id uuid REFERENCES company_profiles(id) ON DELETE CASCADE;
                    ALTER TABLE guest_houses ADD COLUMN IF NOT EXISTS individual_owner_id uuid REFERENCES individual_owners(id) ON DELETE CASCADE;
                    
                    -- Ensure M2M tables exist for GuesthouseProfile
                    DROP TABLE IF EXISTS guest_houses_amenities;
                    DROP TABLE IF EXISTS guest_houses_facility;
                    CREATE TABLE IF NOT EXISTS guest_houses_amenities (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        guesthouseprofile_id uuid NOT NULL REFERENCES guest_houses(id) ON DELETE CASCADE,
                        amenity_id uuid NOT NULL REFERENCES amenities(id) ON DELETE CASCADE,
                        CONSTRAINT guest_houses_amenities_unique UNIQUE (guesthouseprofile_id, amenity_id)
                    );
                    CREATE TABLE IF NOT EXISTS guest_houses_facility (
                        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        guesthouseprofile_id uuid NOT NULL REFERENCES guest_houses(id) ON DELETE CASCADE,
                        facility_id uuid NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
                        CONSTRAINT guest_houses_facility_unique UNIQUE (guesthouseprofile_id, facility_id)
                    );
                    
                    -- Create indexes for performance (matches 0013 expectations)
                    CREATE INDEX IF NOT EXISTS guest_houses_amenities_ghp_idx ON guest_houses_amenities (guesthouseprofile_id);
                    CREATE INDEX IF NOT EXISTS guest_houses_amenities_am_idx ON guest_houses_amenities (amenity_id);
                    CREATE INDEX IF NOT EXISTS guest_houses_facility_ghp_idx ON guest_houses_facility (guesthouseprofile_id);
                    CREATE INDEX IF NOT EXISTS guest_houses_facility_fac_idx ON guest_houses_facility (facility_id);
                    """,
                    reverse_sql="""
                    ALTER TABLE guest_houses DROP COLUMN IF EXISTS address_id;
                    ALTER TABLE guest_houses DROP COLUMN IF EXISTS company_id;
                    ALTER TABLE guest_houses DROP COLUMN IF EXISTS individual_owner_id;
                    DROP TABLE IF EXISTS guest_houses_amenities;
                    DROP TABLE IF EXISTS guest_houses_facility;
                    """
                )
            ],
        ),
        # Phase 2: Cleanup legacy models/fields from state (State only)
        # We do this separately to avoid Django attempting to drop physical tables that are missing or already handled.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name='guesthouselisting', name='address'),
                migrations.RemoveField(model_name='guesthouselisting', name='amenities'),
                migrations.RemoveField(model_name='guesthouselisting', name='company'),
                migrations.RemoveField(model_name='guesthouselisting', name='facility'),
                migrations.RemoveField(model_name='guesthouselisting', name='individual_owner'),
            ],
            database_operations=[],
        ),
        # Phase 3: Apply updates to remaining models (GuesthouseProfile, GuesthouseRoom etc)
        migrations.AlterModelOptions(
            name='guesthousebooking',
            options={'verbose_name': 'Guesthouse Booking', 'verbose_name_plural': 'Guesthouse Bookings'},
        ),
        migrations.AlterModelOptions(
            name='guesthousebookingitem',
            options={'verbose_name': 'Guesthouse Booking Item', 'verbose_name_plural': 'Guesthouse Booking Items'},
        ),
        migrations.AlterField(
            model_name='guesthouseinventory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for this date; falls back to room base price if null.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='address',
            field=models.OneToOneField(help_text='Guesthouse location address', on_delete=django.db.models.deletion.RESTRICT, related_name='guesthouse_profile', to='core.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company that owns this listing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_house_profiles', to='account.companyprofile', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='currency',
            field=models.CharField(default='ETB', help_text="ISO 4217 currency code for the price fields, e.g., 'ETB'.", max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the listing.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='individual_owner',
            field=models.ForeignKey(blank=True, help_text='The individual person that owns this listing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_house_profiles', to='account.individualownerprofile', verbose_name='Individual Owner'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the listing is active and visible.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average rating from user reviews (0–5).', max_digits=3, null=True, verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='title',
            field=models.CharField(help_text="Title of the listing, e.g., 'Luxury Suite with Pool View'.", max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='guesthouseroom',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='guesthouseroom',
            name='currency',
            field=models.CharField(default='ETB', help_text="ISO 4217 currency code for the price fields, e.g., 'ETB'.", max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='guesthouseroom',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the listing.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='guesthouseroom',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the listing is active and visible.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='guesthouseroom',
            name='title',
            field=models.CharField(help_text="Title of the listing, e.g., 'Luxury Suite with Pool View'.", max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='guesthouseroom',
            name='total_units',
            field=models.PositiveIntegerField(default=1, help_text='How many rooms of this type exist in the guest house.', verbose_name='Total Rooms of This Type'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='guesthousebooking',
                    table='guest_house_bookings',
                ),
                migrations.AlterModelTable(
                    name='guesthousebookingitem',
                    table='guest_house_booking_items',
                ),
            ],
            database_operations=[],
        ),
        # Phase 4: Cleanup state (State only)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name='GuestHouseAvailability'),
                migrations.DeleteModel(name='GuestHouseListing'),
            ],
            database_operations=[],
        ),
    ]
