# Generated by Django 5.2.4 on 2026-01-20 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_companyprofile_address_and_more'),
        ('core', '0003_alter_address_country'),
        ('listing', '0013_create_guesthouse_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guesthouselisting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='guesthouselisting',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='guesthouselisting',
            name='company',
        ),
        migrations.RemoveField(
            model_name='guesthouselisting',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='guesthouselisting',
            name='individual_owner',
        ),
        migrations.AlterField(
            model_name='guesthouseinventory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for this date; falls back to room base price if null.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='address',
            field=models.OneToOneField(help_text='Guesthouse location address', on_delete=django.db.models.deletion.RESTRICT, related_name='guesthouse_profile', to='core.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='company',
            field=models.ForeignKey(blank=True, help_text='The company that owns this listing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_house_profiles', to='account.companyprofile', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='currency',
            field=models.CharField(default='ETB', help_text="ISO 4217 currency code for the price fields, e.g., 'ETB'.", max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the listing.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='individual_owner',
            field=models.ForeignKey(blank=True, help_text='The individual person that owns this listing.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_house_profiles', to='account.individualownerprofile', verbose_name='Individual Owner'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the listing is active and visible.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average rating from user reviews (0–5).', max_digits=3, null=True, verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='title',
            field=models.CharField(help_text="Title of the listing, e.g., 'Luxury Suite with Pool View'.", max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='guesthouseroom',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='guesthouseroom',
            name='currency',
            field=models.CharField(default='ETB', help_text="ISO 4217 currency code for the price fields, e.g., 'ETB'.", max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='guesthouseroom',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the listing.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='guesthouseroom',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the listing is active and visible.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='guesthouseroom',
            name='title',
            field=models.CharField(help_text="Title of the listing, e.g., 'Luxury Suite with Pool View'.", max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='guesthouseroom',
            name='total_units',
            field=models.PositiveIntegerField(default=1, help_text='How many rooms of this type exist in the guest house.', verbose_name='Total Rooms of This Type'),
        ),
        migrations.DeleteModel(
            name='GuestHouseAvailability',
        ),
        migrations.DeleteModel(
            name='GuestHouseListing',
        ),
    ]
