# Generated by Django 5.2.4 on 2026-01-23 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_remove_guesthouselisting_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='carrental',
                    table='car_rentals',
                ),
                migrations.AlterField(
                    model_name='booking',
                    name='user',
                    field=models.ForeignKey(blank=True, help_text='User account of the person making the booking (if logged in)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Booker Account'),
                ),
                migrations.AlterField(
                    model_name='carrental',
                    name='renter',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Renter Account'),
                ),
                migrations.AlterField(
                    model_name='eventspacebooking',
                    name='user',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Booker Account'),
                ),
                migrations.AlterField(
                    model_name='guesthousebooking',
                    name='renter',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Renter Account'),
                ),
            ],
            database_operations=[],
        ),
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(help_text="e.g., 'Breakfast', 'Airport Pickup', 'Extra Bed'", max_length=100, verbose_name='Addon Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the addon', verbose_name='Description')),
                ('category', models.CharField(choices=[('meal', 'Meal/Food'), ('transport', 'Transportation'), ('service', 'Service'), ('amenity', 'Amenity/Equipment')], default='service', max_length=20, verbose_name='Category')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units (e.g., 2 breakfasts)', verbose_name='Quantity')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price for one unit of this addon', max_digits=10, verbose_name='Price per Unit')),
            ],
            options={
                'verbose_name': 'Booking Addon',
                'verbose_name_plural': 'Booking Addons',
                'db_table': 'booking_addons',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=10, verbose_name='Booking Reference'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Guest Email'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Guest First Name'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Guest Last Name'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Guest Phone Number'),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, default='', verbose_name='Special Requests'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=10, verbose_name='Booking Reference'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Guest Email'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='guest_first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Guest First Name'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='guest_last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Guest Last Name'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Guest Phone Number'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carrental',
            name='special_requests',
            field=models.TextField(blank=True, default='', verbose_name='Special Requests'),
        ),
        migrations.AddField(
            model_name='eventspacebooking',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=10, verbose_name='Booking Reference'),
        ),
        migrations.AddField(
            model_name='eventspacebooking',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Guest Email'),
        ),
        migrations.AddField(
            model_name='eventspacebooking',
            name='guest_first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Guest First Name'),
        ),
        migrations.AddField(
            model_name='eventspacebooking',
            name='guest_last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Guest Last Name'),
        ),
        migrations.AddField(
            model_name='eventspacebooking',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Guest Phone Number'),
        ),
        migrations.AddField(
            model_name='eventspacebooking',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventspacebooking',
            name='special_requests',
            field=models.TextField(blank=True, default='', verbose_name='Special Requests'),
        ),
        migrations.AddField(
            model_name='guesthousebooking',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=10, verbose_name='Booking Reference'),
        ),
        migrations.AddField(
            model_name='guesthousebooking',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Guest Email'),
        ),
        migrations.AddField(
            model_name='guesthousebooking',
            name='guest_first_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Guest First Name'),
        ),
        migrations.AddField(
            model_name='guesthousebooking',
            name='guest_last_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Guest Last Name'),
        ),
        migrations.AddField(
            model_name='guesthousebooking',
            name='guest_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Guest Phone Number'),
        ),
        migrations.AddField(
            model_name='guesthousebooking',
            name='snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guesthousebooking',
            name='special_requests',
            field=models.TextField(blank=True, default='', verbose_name='Special Requests'),
        ),
        migrations.AddConstraint(
            model_name='carrental',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='car_rental_valid_dates'),
        ),
        migrations.AddConstraint(
            model_name='guesthousebooking',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='guesthouse_booking_valid_dates'),
        ),
        migrations.AddField(
            model_name='bookingaddon',
            name='booking_item',
            field=models.ForeignKey(help_text='The room/item this addon is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='listing.bookingitem', verbose_name='Booking Item'),
        ),
    ]
