# Generated by Django 5.2.4 on 2025-12-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_guesthouselisting_facility_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guesthousebookingitem',
            options={'verbose_name': 'Guesthouse Booking Item', 'verbose_name_plural': 'GuestBooking Items'},
        ),
        migrations.AlterModelTable(
            name='guesthousebookingitem',
            table='guesthouse_booking_items',
        ),
    ]
