# Generated by Django 5.2.4 on 2026-01-23 18:20

from django.db import migrations
from apps.listing.utils import generate_booking_reference


def backfill_booking_data(apps, schema_editor):
    """
    Backfill guest data and generate booking references for all existing bookings.
    """
    # Get model classes
    Booking = apps.get_model('listing', 'Booking')
    GuestHouseBooking = apps.get_model('listing', 'GuestHouseBooking')
    EventSpaceBooking = apps.get_model('listing', 'EventSpaceBooking')
    CarRental = apps.get_model('listing', 'CarRental')
    
    # 1. Hotel Bookings
    print(f"\nBackfilling {Booking.objects.count()} hotel bookings...")
    for booking in Booking.objects.select_related('user').all():
        if not booking.booking_reference:
            booking.booking_reference = generate_booking_reference(prefix='H', model_class=Booking)
        
        if booking.user and not booking.guest_email:
            booking.guest_email = booking.user.email
            booking.guest_first_name = booking.user.first_name or "Guest"
            booking.guest_last_name = booking.user.last_name or "User"
        
        booking.save(update_fields=[
            'booking_reference', 'guest_email', 
            'guest_first_name', 'guest_last_name'
        ])
    
    # 2. Guesthouse Bookings
    print(f"Backfilling {GuestHouseBooking.objects.count()} guesthouse bookings...")
    for booking in GuestHouseBooking.objects.select_related('renter').all():
        if not booking.booking_reference:
            booking.booking_reference = generate_booking_reference(prefix='G', model_class=GuestHouseBooking)
        
        if booking.renter and not booking.guest_email:
            booking.guest_email = booking.renter.email
            booking.guest_first_name = booking.renter.first_name or "Guest"
            booking.guest_last_name = booking.renter.last_name or "User"
        
        booking.save(update_fields=[
            'booking_reference', 'guest_email',
            'guest_first_name', 'guest_last_name'
        ])
    
    # 3. Event Space Bookings
    print(f"Backfilling {EventSpaceBooking.objects.count()} event space bookings...")
    for booking in EventSpaceBooking.objects.select_related('user').all():
        if not booking.booking_reference:
            booking.booking_reference = generate_booking_reference(prefix='E', model_class=EventSpaceBooking)
        
        if booking.user and not booking.guest_email:
            booking.guest_email = booking.user.email
            booking.guest_first_name = booking.user.first_name or "Guest"
            booking.guest_last_name = booking.user.last_name or "User"
        
        booking.save(update_fields=[
            'booking_reference', 'guest_email',
            'guest_first_name', 'guest_last_name'
        ])
    
    # 4. Car Rentals
    print(f"Backfilling {CarRental.objects.count()} car rentals...")
    for rental in CarRental.objects.select_related('renter').all():
        if not rental.booking_reference:
            rental.booking_reference = generate_booking_reference(prefix='C', model_class=CarRental)
        
        if rental.renter and not rental.guest_email:
            rental.guest_email = rental.renter.email
            rental.guest_first_name = rental.renter.first_name or "Guest"
            rental.guest_last_name = rental.renter.last_name or "User"
        
        rental.save(update_fields=[
            'booking_reference', 'guest_email',
            'guest_first_name', 'guest_last_name'
        ])
    
    print("✓ Data backfill complete!")


def reverse_backfill(apps, schema_editor):
    """No reverse operation needed - data backfill is safe to keep."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_add_guest_checkout_features'),
    ]

    operations = [
        migrations.RunPython(backfill_booking_data, reverse_backfill),
    ]
