# Generated by Django 5.2.4 on 2026-01-23 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0016_backfill_booking_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, help_text='Human-readable booking code (e.g., H-X7Y2Z9)', max_length=10, unique=True, verbose_name='Booking Reference'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(blank=True, default='', help_text='Email address for booking confirmations and communication', max_length=254, verbose_name='Guest Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_first_name',
            field=models.CharField(blank=True, default='', help_text='First name of the person staying', max_length=100, verbose_name='Guest First Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_last_name',
            field=models.CharField(blank=True, default='', help_text='Last name of the person staying', max_length=100, verbose_name='Guest Last Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(blank=True, default='', help_text='Contact phone number for the guest', max_length=20, verbose_name='Guest Phone Number'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, default='', help_text='Guest requests (e.g., late check-in, non-smoking room, dietary needs)', verbose_name='Special Requests'),
        ),
        migrations.AlterField(
            model_name='carrental',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=10, unique=True, verbose_name='Booking Reference'),
        ),
        migrations.AlterField(
            model_name='eventspacebooking',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=10, unique=True, verbose_name='Booking Reference'),
        ),
        migrations.AlterField(
            model_name='guesthousebooking',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=10, unique=True, verbose_name='Booking Reference'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False), ('guest_email__isnull', False), _connector='OR'), name='booking_must_have_user_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='carrental',
            constraint=models.CheckConstraint(condition=models.Q(('renter__isnull', False), ('guest_email__isnull', False), _connector='OR'), name='car_rental_must_have_renter_or_guest'),
        ),
        migrations.AddConstraint(
            model_name='guesthousebooking',
            constraint=models.CheckConstraint(condition=models.Q(('renter__isnull', False), ('guest_email__isnull', False), _connector='OR'), name='guesthouse_booking_must_have_renter_or_guest'),
        ),
    ]
