# Generated by Django 5.2.4 on 2026-01-25 12:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_companyprofile_address_and_more'),
        ('listing', '0017_enforce_guest_booking_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingaddon',
            name='currency',
            field=models.CharField(default='ETB', help_text='Currency code (snapshot at booking time)', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='bookingaddon',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, help_text='Price for one unit of this addon (snapshot at booking time)', max_digits=10, verbose_name='Price per Unit'),
        ),
        migrations.CreateModel(
            name='AddonOffering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(help_text="e.g., 'Breakfast Buffet', 'Airport Shuttle'", max_length=100, verbose_name='Addon Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the addon service', verbose_name='Description')),
                ('category', models.CharField(choices=[('meal', 'Meal/Food'), ('transport', 'Transportation'), ('service', 'Service'), ('amenity', 'Amenity/Equipment')], default='service', max_length=20, verbose_name='Category')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Base price for one unit of this addon', max_digits=10, verbose_name='Price per Unit')),
                ('currency', models.CharField(default='ETB', help_text='ISO 4217 currency code', max_length=3, verbose_name='Currency')),
                ('pricing_type', models.CharField(choices=[('per_person', 'Per Person'), ('per_night', 'Per Night'), ('per_booking', 'Per Booking (One-time)'), ('per_unit', 'Per Unit')], default='per_unit', help_text='How this addon is priced', max_length=20, verbose_name='Pricing Type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this addon is currently available for booking', verbose_name='Active')),
                ('max_quantity_per_booking', models.PositiveIntegerField(blank=True, help_text='Maximum number of units per booking (null = unlimited)', null=True, verbose_name='Max Quantity per Booking')),
                ('requires_inventory', models.BooleanField(default=False, help_text='Whether this addon has limited daily inventory', verbose_name='Requires Inventory')),
                ('daily_capacity', models.PositiveIntegerField(blank=True, help_text='Total available units per day (if inventory tracked)', null=True, verbose_name='Daily Capacity')),
                ('icon', models.CharField(blank=True, help_text="Icon identifier for frontend (e.g., 'breakfast', 'shuttle')", max_length=50, verbose_name='Icon')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which addon appears in lists (lower numbers first)', verbose_name='Display Order')),
                ('hotel', models.ForeignKey(help_text='The hotel that provides this addon', on_delete=django.db.models.deletion.CASCADE, related_name='addon_offerings', to='account.hotelprofile', verbose_name='Hotel')),
            ],
            options={
                'verbose_name': 'Addon Offering',
                'verbose_name_plural': 'Addon Offerings',
                'db_table': 'addon_offerings',
                'ordering': ['hotel', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bookingaddon',
            name='offering',
            field=models.ForeignKey(blank=True, help_text="Reference to the hotel's addon offering definition (null for legacy bookings)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_instances', to='listing.addonoffering', verbose_name='Addon Offering'),
        ),
        migrations.AddIndex(
            model_name='addonoffering',
            index=models.Index(fields=['hotel', 'is_active'], name='addon_offer_hotel_i_340fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='addonoffering',
            index=models.Index(fields=['category'], name='addon_offer_categor_236011_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addonoffering',
            unique_together={('hotel', 'name')},
        ),
    ]
