# Generated by Django 5.2.4 on 2026-01-27 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_company_user_individual_owner_and_more'),
        ('listing', '0018_add_addon_offerings_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='account.companyprofile'),
        ),
        migrations.AddField(
            model_name='season',
            name='individual_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='account.individualownerprofile'),
        ),
    ]
