# Generated by Django 5.2.4 on 2026-01-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_company_user_individual_owner_and_more'),
        ('listing', '0019_season_company_season_individual_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalrate',
            name='individual_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_rates', to='account.individualownerprofile'),
        ),
    ]
