# Generated by Django 5.2.4 on 2026-02-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0022_force_null_with_sql'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouseprofile',
            name='license',
            field=models.FileField(blank=True, help_text='Upload a valid business license (PDF/Image).', null=True, upload_to='guesthouse/licenses/', verbose_name='Business License'),
        ),
        migrations.AddField(
            model_name='guesthouseprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number for the guest house.', max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='guesthouseprofile',
            name='website',
            field=models.URLField(blank=True, help_text='Official website URL.', null=True, verbose_name='Website'),
        ),
    ]
