# Generated by Django 5.2.4 on 2026-02-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0023_guesthouseprofile_license_guesthouseprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guesthouseprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='guesthouse/logos/', verbose_name='Logo'),
        ),
    ]
