# Generated by Django 5.2.4 on 2026-02-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0024_guesthouseprofile_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlisting',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='eventspacelisting',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='guesthouseprofile',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='guesthouseroom',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='propertylisting',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, null=True, verbose_name='Price'),
        ),
    ]
