# Generated by Django 5.2.4 on 2026-06-06 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0026_drop_guesthouse_total_rooms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the listing has been verified by an administrator.', verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the listing was last verified by an administrator.', null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who last verified this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='eventspacelisting',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the listing has been verified by an administrator.', verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='eventspacelisting',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the listing was last verified by an administrator.', null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='eventspacelisting',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who last verified this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='guesthouseprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the listing has been verified by an administrator.', verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='guesthouseprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the listing was last verified by an administrator.', null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='guesthouseprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who last verified this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='guesthouseroom',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the listing has been verified by an administrator.', verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='guesthouseroom',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the listing was last verified by an administrator.', null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='guesthouseroom',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who last verified this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the listing has been verified by an administrator.', verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the listing was last verified by an administrator.', null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who last verified this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the listing has been verified by an administrator.', verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the listing was last verified by an administrator.', null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who last verified this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
    ]
