# Generated by Django 5.2.4 on 2026-06-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0027_carlisting_is_verified_carlisting_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='pre_rental_requirements',
            field=models.TextField(blank=True, default='', help_text='Owner-defined instructions or compliance notes that renters must review before booking.', verbose_name='Pre-rental Requirements'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='rental_mode',
            field=models.CharField(choices=[('with_driver', 'With Driver'), ('without_driver', 'Without Driver')], default='with_driver', help_text='Whether the vehicle is rented with a driver or as a self-drive booking.', max_length=32, verbose_name='Rental Mode'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='requires_business_license',
            field=models.BooleanField(default=False, help_text='Whether self-drive renters must provide a business license number.', verbose_name='Requires Business License'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='requires_code_3',
            field=models.BooleanField(default=False, help_text='Whether self-drive renters must provide a Code 3 license/permit.', verbose_name='Requires Code 3'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='renter_business_license_number',
            field=models.CharField(blank=True, default='', help_text='Business license number supplied when required by the owner.', max_length=64, verbose_name='Business License Number'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='renter_code_3_license_number',
            field=models.CharField(blank=True, default='', help_text='Code 3 license/permit number supplied when required by the owner.', max_length=64, verbose_name='Code 3 License Number'),
        ),
        migrations.AddField(
            model_name='carrental',
            name='renter_driver_license_number',
            field=models.CharField(blank=True, default='', help_text='Driver license number supplied for self-drive compliance.', max_length=64, verbose_name='Driver License Number'),
        ),
    ]
