# Generated by Django 5.2.4 on 2026-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0028_carlisting_pre_rental_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='booking_forward_window_days',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of days ahead a booking can start for this listing.', verbose_name='Booking Forward Window Days'),
        ),
        migrations.AddField(
            model_name='eventspacelisting',
            name='booking_forward_window_days',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of days ahead a booking can start for this listing.', verbose_name='Booking Forward Window Days'),
        ),
        migrations.AddField(
            model_name='guesthouseprofile',
            name='booking_forward_window_days',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of days ahead a booking can start for this listing.', verbose_name='Booking Forward Window Days'),
        ),
        migrations.AddField(
            model_name='guesthouseroom',
            name='booking_forward_window_days',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of days ahead a booking can start for this listing.', verbose_name='Booking Forward Window Days'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='booking_forward_window_days',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of days ahead a booking can start for this listing.', verbose_name='Booking Forward Window Days'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='booking_forward_window_days',
            field=models.PositiveIntegerField(default=5, help_text='Maximum number of days ahead a booking can start for this listing.', verbose_name='Booking Forward Window Days'),
        ),
    ]
