# Generated by Django 5.2.4 on 2026-06-10 08:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_phone_change_count_user_phone_last_changed_at'),
        ('listing', '0029_carlisting_booking_forward_window_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSaleListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the listing has been verified by an administrator.', verbose_name='Is Verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the listing was last verified by an administrator.', null=True, verbose_name='Verified At')),
                ('title', models.CharField(help_text="Title of the listing, e.g., 'Luxury Suite with Pool View'.", max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the listing.', verbose_name='Description')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, null=True, verbose_name='Price')),
                ('currency', models.CharField(default='ETB', help_text="ISO 4217 currency code for the price fields, e.g., 'ETB'.", max_length=3, verbose_name='Currency')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the listing is active and visible.', verbose_name='Is Active')),
                ('booking_forward_window_days', models.PositiveIntegerField(default=5, help_text='Maximum number of days ahead a booking can start for this listing.', verbose_name='Booking Forward Window Days')),
                ('brand', models.CharField(choices=[('toyota', 'Toyota'), ('bmw', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('audi', 'Audi'), ('Volkswagen', 'Volkswagen'), ('honda', 'Honda'), ('ford', 'Ford'), ('nissan', 'Nissan'), ('chevrolet', 'Chevrolet'), ('kia', 'Kia'), ('hyundai', 'Hyundai'), ('volvo', 'Volvo'), ('jeep', 'Jeep'), ('porsche', 'Porsche'), ('lexus', 'Lexus'), ('mazda', 'Mazda'), ('land_rover', 'Land Rover'), ('subaru', 'Subaru'), ('fiat', 'Fiat'), ('peugeot', 'Peugeot')], max_length=100, verbose_name='Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('mileage', models.PositiveIntegerField(verbose_name='Mileage (km)')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('electric', 'Electric'), ('petrol', 'Petrol'), ('hybrid', 'Hybrid')], max_length=50, verbose_name='Engine Type')),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=50, verbose_name='Transmission')),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('used', 'Used')], max_length=200, verbose_name='Condition')),
                ('car_class', models.CharField(choices=[('luxury', 'Luxury'), ('normal', 'Normal')], default='normal', max_length=200, verbose_name='Class Category')),
                ('seats', models.PositiveSmallIntegerField(default=3)),
                ('seller_contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('seller_phone', models.CharField(max_length=20)),
                ('seller_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reveal_fee', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_sale_listings', to='account.companyprofile', verbose_name='Company')),
                ('individual_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_sale_listings', to='account.individualownerprofile', verbose_name='Individual Owner')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Administrator who last verified this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Car Sale Listing',
                'verbose_name_plural': 'Car Sale Listings',
                'db_table': 'car_sale_listings',
            },
        ),
        migrations.CreateModel(
            name='ContactRevealRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('status', models.CharField(choices=[('reveal_requested', 'Reveal Requested'), ('payment_initiated', 'Payment Initiated'), ('paid_revealed', 'Paid Revealed'), ('expired', 'Expired')], default='reveal_requested', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('buyer_note', models.TextField(blank=True, default='')),
                ('buyer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('tx_ref', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('contact_snapshot', models.JSONField(blank=True, default=dict)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_reveal_requests', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_reveal_requests', to='listing.carsalelisting')),
            ],
            options={
                'verbose_name': 'Contact Reveal Request',
                'verbose_name_plural': 'Contact Reveal Requests',
                'db_table': 'contact_reveal_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='carsalelisting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('individual_owner__isnull', False), ('company__isnull', True)), models.Q(('individual_owner__isnull', True), ('company__isnull', False)), _connector='OR'), name='car_sale_owner_must_exist'),
        ),
        migrations.AddIndex(
            model_name='contactrevealrequest',
            index=models.Index(fields=['buyer', 'listing', 'status'], name='contact_rev_buyer_i_cafb1f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrevealrequest',
            index=models.Index(fields=['tx_ref'], name='contact_rev_tx_ref_3ace9b_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrevealrequest',
            index=models.Index(fields=['expires_at'], name='contact_rev_expires_7148af_idx'),
        ),
    ]
