# Generated by Django 5.2.4 on 2026-06-11 07:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_phone_change_count_user_phone_last_changed_at'),
        ('core', '0004_address_google_place_id'),
        ('listing', '0030_carsalelisting_contactrevealrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySaleListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the listing has been verified by an administrator.', verbose_name='Is Verified')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When the listing was last verified by an administrator.', null=True, verbose_name='Verified At')),
                ('title', models.CharField(help_text="Title of the listing, e.g., 'Luxury Suite with Pool View'.", max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the listing.', verbose_name='Description')),
                ('base_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the service/product (if applicable).', max_digits=10, null=True, verbose_name='Price')),
                ('currency', models.CharField(default='ETB', help_text="ISO 4217 currency code for the price fields, e.g., 'ETB'.", max_length=3, verbose_name='Currency')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the listing is active and visible.', verbose_name='Is Active')),
                ('booking_forward_window_days', models.PositiveIntegerField(default=5, help_text='Maximum number of days ahead a booking can start for this listing.', verbose_name='Booking Forward Window Days')),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('condo', 'Condo'), ('villa', 'Villa'), ('house', 'House'), ('land', 'Land'), ('commercial', 'Commercial'), ('other', 'Other')], max_length=50, verbose_name='Property Type')),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('square_meters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('land_size_square_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_furnished', models.BooleanField(default=False)),
                ('seller_contact_name', models.CharField(blank=True, default='', max_length=150)),
                ('seller_phone', models.CharField(max_length=20)),
                ('seller_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reveal_fee', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='property_sale_listing', to='core.address', verbose_name='Address')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_sale_listings', to='account.companyprofile', verbose_name='Company')),
                ('individual_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_sale_listings', to='account.individualownerprofile', verbose_name='Individual Owner')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Administrator who last verified this listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Property Sale Listing',
                'verbose_name_plural': 'Property Sale Listings',
                'db_table': 'property_sale_listings',
            },
        ),
        migrations.CreateModel(
            name='PropertyContactRevealRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('status', models.CharField(choices=[('reveal_requested', 'Reveal Requested'), ('payment_initiated', 'Payment Initiated'), ('paid_revealed', 'Paid Revealed'), ('expired', 'Expired')], default='reveal_requested', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('buyer_note', models.TextField(blank=True, default='')),
                ('buyer_phone', models.CharField(blank=True, default='', max_length=20)),
                ('tx_ref', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('contact_snapshot', models.JSONField(blank=True, default=dict)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_contact_reveal_requests', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_reveal_requests', to='listing.propertysalelisting')),
            ],
            options={
                'verbose_name': 'Property Contact Reveal Request',
                'verbose_name_plural': 'Property Contact Reveal Requests',
                'db_table': 'property_contact_reveal_requests',
            },
        ),
        migrations.AddConstraint(
            model_name='propertysalelisting',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('individual_owner__isnull', False), ('company__isnull', True)), models.Q(('individual_owner__isnull', True), ('company__isnull', False)), _connector='OR'), name='property_sale_owner_must_exist'),
        ),
        migrations.AddIndex(
            model_name='propertycontactrevealrequest',
            index=models.Index(fields=['listing', 'buyer', 'status'], name='property_co_listing_70cc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='propertycontactrevealrequest',
            index=models.Index(fields=['tx_ref'], name='property_co_tx_ref_0f15f2_idx'),
        ),
        migrations.AddIndex(
            model_name='propertycontactrevealrequest',
            index=models.Index(fields=['expires_at'], name='property_co_expires_0987ef_idx'),
        ),
    ]
