# Generated by Django 5.2.4 on 2026-06-11 08:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0031_propertysalelisting_propertycontactrevealrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyRentalAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('date', models.DateField(db_index=True)),
                ('available_units', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price for this date; falls back to property base price if null.', max_digits=10, null=True)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_availabilities', to='listing.propertylisting')),
            ],
            options={
                'verbose_name': 'Property Rental Availability',
                'verbose_name_plural': 'Property Rental Availabilities',
                'db_table': 'property_rental_availabilities',
                'indexes': [models.Index(fields=['property_listing', 'date'], name='property_re_propert_e5a5c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('property_listing', 'date'), name='property_rental_listing_date_unique'), models.CheckConstraint(condition=models.Q(('available_units__gte', 0)), name='property_rental_availability_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='PropertyRentalBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('guest_first_name', models.CharField(blank=True, default='', max_length=100)),
                ('guest_last_name', models.CharField(blank=True, default='', max_length=100)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('guest_phone', models.CharField(blank=True, default='', max_length=20)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('booking_reference', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=10, unique=True, verbose_name='Booking Reference')),
                ('snapshot', models.JSONField(blank=True, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_version', models.CharField(blank=True, max_length=50)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_content_snapshot', models.TextField(blank=True, null=True)),
                ('property_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_bookings', to='listing.propertylisting')),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Renter Account')),
            ],
            options={
                'verbose_name': 'Property Rental Booking',
                'verbose_name_plural': 'Property Rental Bookings',
                'db_table': 'property_rental_bookings',
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='property_rental_booking_valid_dates'), models.CheckConstraint(condition=models.Q(('renter__isnull', False), ('guest_email__isnull', False), _connector='OR'), name='property_rental_booking_must_have_renter_or_guest')],
            },
        ),
    ]
