# Generated by Django 5.2.4 on 2026-06-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0032_propertyrentalavailability_propertyrentalbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='verification_note',
            field=models.CharField(blank=True, help_text='Optional note recorded by an administrator during verification.', max_length=500, null=True, verbose_name='Verification Note'),
        ),
        migrations.AddField(
            model_name='carsalelisting',
            name='verification_note',
            field=models.CharField(blank=True, help_text='Optional note recorded by an administrator during verification.', max_length=500, null=True, verbose_name='Verification Note'),
        ),
        migrations.AddField(
            model_name='eventspacelisting',
            name='verification_note',
            field=models.CharField(blank=True, help_text='Optional note recorded by an administrator during verification.', max_length=500, null=True, verbose_name='Verification Note'),
        ),
        migrations.AddField(
            model_name='guesthouseprofile',
            name='verification_note',
            field=models.CharField(blank=True, help_text='Optional note recorded by an administrator during verification.', max_length=500, null=True, verbose_name='Verification Note'),
        ),
        migrations.AddField(
            model_name='guesthouseroom',
            name='verification_note',
            field=models.CharField(blank=True, help_text='Optional note recorded by an administrator during verification.', max_length=500, null=True, verbose_name='Verification Note'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='verification_note',
            field=models.CharField(blank=True, help_text='Optional note recorded by an administrator during verification.', max_length=500, null=True, verbose_name='Verification Note'),
        ),
        migrations.AddField(
            model_name='propertysalelisting',
            name='verification_note',
            field=models.CharField(blank=True, help_text='Optional note recorded by an administrator during verification.', max_length=500, null=True, verbose_name='Verification Note'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='verification_note',
            field=models.CharField(blank=True, help_text='Optional note recorded by an administrator during verification.', max_length=500, null=True, verbose_name='Verification Note'),
        ),
    ]
