# Generated by Django 5.2.4 on 2026-06-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0033_carlisting_verification_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='address_components',
            field=models.JSONField(blank=True, null=True, verbose_name='Address Components'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Formatted Address'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='place_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Place ID'),
        ),
        migrations.AddField(
            model_name='carsalelisting',
            name='address_components',
            field=models.JSONField(blank=True, null=True, verbose_name='Address Components'),
        ),
        migrations.AddField(
            model_name='carsalelisting',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Formatted Address'),
        ),
        migrations.AddField(
            model_name='carsalelisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='carsalelisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='carsalelisting',
            name='place_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Place ID'),
        ),
        migrations.AddField(
            model_name='eventspacelisting',
            name='address_components',
            field=models.JSONField(blank=True, null=True, verbose_name='Address Components'),
        ),
        migrations.AddField(
            model_name='eventspacelisting',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Formatted Address'),
        ),
        migrations.AddField(
            model_name='eventspacelisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='eventspacelisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='eventspacelisting',
            name='place_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Place ID'),
        ),
        migrations.AddField(
            model_name='guesthouseprofile',
            name='address_components',
            field=models.JSONField(blank=True, null=True, verbose_name='Address Components'),
        ),
        migrations.AddField(
            model_name='guesthouseprofile',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Formatted Address'),
        ),
        migrations.AddField(
            model_name='guesthouseprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='guesthouseprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='guesthouseprofile',
            name='place_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Place ID'),
        ),
        migrations.AddField(
            model_name='guesthouseroom',
            name='address_components',
            field=models.JSONField(blank=True, null=True, verbose_name='Address Components'),
        ),
        migrations.AddField(
            model_name='guesthouseroom',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Formatted Address'),
        ),
        migrations.AddField(
            model_name='guesthouseroom',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='guesthouseroom',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='guesthouseroom',
            name='place_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Place ID'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='address_components',
            field=models.JSONField(blank=True, null=True, verbose_name='Address Components'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Formatted Address'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='place_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Place ID'),
        ),
        migrations.AddField(
            model_name='propertysalelisting',
            name='address_components',
            field=models.JSONField(blank=True, null=True, verbose_name='Address Components'),
        ),
        migrations.AddField(
            model_name='propertysalelisting',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Formatted Address'),
        ),
        migrations.AddField(
            model_name='propertysalelisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='propertysalelisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='propertysalelisting',
            name='place_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Place ID'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='address_components',
            field=models.JSONField(blank=True, null=True, verbose_name='Address Components'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Formatted Address'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='place_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Place ID'),
        ),
    ]
