# Generated by Django 5.2.4 on 2026-06-14 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0034_carlisting_address_components_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrevealrequest',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_reveal_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertycontactrevealrequest',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_contact_reveal_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
