# Generated by Django 5.2.4 on 2026-06-15 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0037_allow_guest_booking_with_phone_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalExtensionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('original_end_date', models.DateField(verbose_name='Original End Date')),
                ('requested_end_date', models.DateField(verbose_name='Requested End Date')),
                ('extra_days', models.PositiveIntegerField(verbose_name='Extra Days')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Extension Amount')),
                ('currency', models.CharField(default='ETB', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('payment_initiated', 'Payment Initiated'), ('paid_applied', 'Paid & Applied'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='requested', max_length=30, verbose_name='Status')),
                ('tx_ref', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('availability_held', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='listing.carrental', verbose_name='Car Rental')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_rental_extension_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Car Rental Extension Request',
                'verbose_name_plural': 'Car Rental Extension Requests',
                'db_table': 'car_rental_extension_requests',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('requested_end_date__gt', models.F('original_end_date'))), name='car_rental_extension_requested_end_after_original_end'), models.CheckConstraint(condition=models.Q(('extra_days__gt', 0)), name='car_rental_extension_extra_days_positive')],
            },
        ),
    ]
