# Generated by Django 5.2.4 on 2026-06-21 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_terms_lifecycle(apps, schema_editor):
    TermsAndConditions = apps.get_model("listing", "TermsAndConditions")

    for terms in TermsAndConditions.objects.all().iterator():
        if terms.is_active:
            terms.status = "active"
            if not terms.published_at:
                terms.published_at = terms.created_at
        else:
            terms.status = "archived"
            if not terms.archived_at:
                terms.archived_at = terms.updated_at

        terms.save(update_fields=["status", "published_at", "archived_at"])


def reverse_backfill_terms_lifecycle(apps, schema_editor):
    TermsAndConditions = apps.get_model("listing", "TermsAndConditions")
    TermsAndConditions.objects.filter(status="active").update(status="draft")
    TermsAndConditions.objects.exclude(is_active=True).update(status="draft", archived_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0038_carrentalextensionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandconditions',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When this version was archived', null=True, verbose_name='Archived At'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms_documents_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Optional provider note for this version', verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this version was published', null=True, verbose_name='Published At'),
        ),
        migrations.AddField(
            model_name='termsandconditions',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', help_text='Lifecycle state for this version', max_length=20, verbose_name='Status'),
        ),
        migrations.RunPython(backfill_terms_lifecycle, reverse_backfill_terms_lifecycle),
    ]
