# Generated by Django 5.2.4 on 2026-06-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0039_termsandconditions_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='business_license_document',
            field=models.FileField(blank=True, help_text='Provider-owned business license document required when self-drive rentals enforce business-license validation.', null=True, upload_to='car/business_licenses/', verbose_name='Business License Document'),
        ),
    ]
