services:
  db:
    image: postgres:18.0
    container_name: michot_db_staging
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - marefiya_pgdata_staging:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: marefiya_redis_staging
    command: redis-server --appendonly yes
    volumes:
      - marefiya_redis_data_staging:/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: michot_pgadmin_staging
    ports:
      - "127.0.0.1:8002:80"
    env_file:
      - .env
    volumes:
      - marefiya_pgadmin_data_staging:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    image: marefiya_staging:dev
    container_name: michot-api-staging
    ports:
      - "127.0.0.1:8005:8000"
    volumes:
      - ./:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./mediafiles:/usr/src/app/mediafiles
    user: "${UID}:${GID}"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  celery:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    image: marefiya_staging:dev
    container_name: michot_celery_staging
    command: celery -A config.celery worker -l info
    volumes:
      - ./:/usr/src/app
    user: "${UID}:${GID}"
    env_file:
      - .env
    depends_on:
      - redis
      - api

  celery-beat:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    image: marefiya_staging:dev
    container_name: michot_celery_beat_staging
    command: celery -A config.celery beat -l info
    depends_on:
      - api
      - redis
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app

volumes:
  marefiya_pgdata_staging:
  marefiya_pgadmin_data_staging:
  marefiya_redis_data_staging:
