services:
  db:
    image: postgres:18.0
    container_name: michot_db_prod
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - marefiya_pgdata_prod:/var/lib/postgresql

  redis:
    image: redis:7-alpine
    container_name: marefiya_redis_prod
    command: redis-server --appendonly yes
    volumes:
      - marefiya_redis_data_prod:/data

  pgadmin4:
    image: dpage/pgadmin4
    container_name: michot_pgadmin_prod
    ports:
      - "127.0.0.1:8008:80"
    env_file:
      - .env
    volumes:
      - marefiya_pgadmin_data_prod:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    image: marefiya_prod:latest
    container_name: michot-api-prod
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./mediafiles:/usr/src/app/mediafiles
    user: "${UID}:${GID}"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
    depends_on:
      db:
        condition: service_healthy

  celery:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    image: marefiya_prod:latest
    container_name: michot_celery_prod
    command: celery -A config.celery worker -l info
    volumes:
      - ./:/usr/src/app
    user: "${UID}:${GID}"
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
    depends_on:
      - redis
      - api

  celery-beat:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    image: marefiya_prod:latest
    container_name: michot_celery_beat_prod
    command: celery -A config.celery beat -l info
    depends_on:
      - api
      - redis
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
    volumes:
      - ./:/usr/src/app

volumes:
  marefiya_pgdata_prod:
  marefiya_pgadmin_data_prod:
  marefiya_redis_data_prod:
