services:
  db:
    image: postgres:18.0
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - marefiya_pgdata:/var/lib/postgresql
  redis:  # <-- NEW REDIS SERVICE
      image: redis:7-alpine
      container_name: marefiya_redis
      command: redis-server --appendonly yes
      volumes:
        - marefiya_redis_data:/data # Volume for persistence
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "127.0.0.1:8001:80"
    env_file:
      - .env
    volumes:
      - marefiya_pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    image: marefiya:dev
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./:/usr/src/app
      - ./staticfiles:/usr/src/app/staticfiles
      - ./mediafiles:/usr/src/app/mediafiles
    user: "${UID}:${GID}"
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000

    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  celery: # <--  new task executor service
      build:
        context: .
        dockerfile: ./docker/prod/Dockerfile
        args:
          USER_ID: ${UID}
          GROUP_ID: ${GID}
      image: marefiya:dev
      # The command runs the Celery worker, pointing to your new app instance
      command: celery -A config.celery worker -l info
      volumes:
        - ./:/usr/src/app
      user: "${UID}:${GID}"
      env_file:
        - .env
      depends_on:
        - redis
        - api # Ensure Django is built before Celery starts looking for tasks
  celery-beat: #new  task scheduler Sevice
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    command: celery -A config.celery beat -l info
    depends_on:
      - api
      - redis
    env_file:
      - .env
    volumes:
      - ./:/usr/src/app
volumes:
  marefiya_pgdata:
  marefiya_pgadmin_data:
  marefiya_redis_data: # <-- NEW VOLUME FOR REDIS PERSISTENCE
