# Generated by Django 5.2.4 on 2025-12-29 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyrate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date when this rate was recorded.', verbose_name='rate date'),
        ),
    ]
