# Generated by Django 5.2.4 on 2026-01-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_currencyrate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='Ethiopia', max_length=100, verbose_name='Country'),
        ),
    ]
