# Generated by Django 5.2.4 on 2025-12-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='company_licenses/', verbose_name='License'),
        ),
    ]
