# Generated by Django 5.2.4 on 2025-12-17 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='business_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Business License Number'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tin',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Tin'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='license',
            field=models.FileField(blank=True, null=True, upload_to='company_licenses/', verbose_name='License'),
        ),
    ]
