# Generated by Django 5.2.4 on 2025-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualownerprofile',
            name='category',
        ),
        migrations.AlterField(
            model_name='individualownerprofile',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='individualownerprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='Phone Number'),
        ),
    ]
