# Generated by Django 5.2.4 on 2025-09-20 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelprofile',
            options={'verbose_name': 'Hotel Profile', 'verbose_name_plural': 'Hotel Profiles'},
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='category',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('pension', 'Pension')], default='hotel', max_length=100, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='category',
            field=models.CharField(choices=[('guest_house', 'Guest House'), ('real_estate', 'Real Estate'), ('apartment', 'Apartment'), ('vehicle', 'Vehicle')], max_length=100, verbose_name='Category'),
        ),
    ]
