# Generated by Django 5.2.4 on 2025-08-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_companyprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='license',
            field=models.FileField(upload_to='company_licenses/', verbose_name='License'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo'),
        ),
    ]
