# Generated by Django 5.2.4 on 2025-11-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='featured',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
