# Generated by Django 5.2.4 on 2025-10-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_individualownerprofile_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='category',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('pension', 'Pension'), ('house', 'House'), ('vehicle', 'Vehicle')], max_length=100, verbose_name='Category'),
        ),
    ]
