# Generated by Django 5.2.4 on 2025-12-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_companyprofile_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='tin',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Tin'),
        ),
    ]
