# Generated by Django 5.2.4 on 2026-01-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_companyprofile_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='chapa_subaccount_id',
            field=models.CharField(blank=True, help_text='The subaccount ID for split payments (e.g., specific to this company).', max_length=100, null=True, verbose_name='Chapa Subaccount ID'),
        ),
        migrations.AddField(
            model_name='individualownerprofile',
            name='chapa_subaccount_id',
            field=models.CharField(blank=True, help_text='The subaccount ID for split payments (e.g., specific to this owner).', max_length=100, null=True, verbose_name='Chapa Subaccount ID'),
        ),
    ]
