# Generated by Django 5.2.4 on 2025-12-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_hotelprofile_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_roles', to='account.role'),
        ),
    ]
