# Generated by Django 5.2.4 on 2026-01-07 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_companyprofile_chapa_subaccount_id_and_more'),
        ('core', '0003_alter_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.OneToOneField(help_text='Company headquarters address', on_delete=django.db.models.deletion.RESTRICT, related_name='company_profile', to='core.address', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='individualownerprofile',
            name='address',
            field=models.OneToOneField(help_text='Individual owner primary address', on_delete=django.db.models.deletion.RESTRICT, related_name='individual_owner_profile', to='core.address', verbose_name='Address'),
        ),
    ]
