# Generated by Django 5.2.4 on 2025-12-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_companyprofile_tin'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='business_license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Business License Number'),
        ),
    ]
