# Generated by Django 5.2.4 on 2025-10-14 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_companyprofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelprofile',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='account.companyprofile'),
        ),
    ]
