# Generated by Django 5.2.4 on 2026-01-27 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_companyprofile_address_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this staff member belongs to (for hired employees)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='account.companyprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='individual_owner',
            field=models.ForeignKey(blank=True, help_text='Individual owner this staff works for (for small guesthouses/rentals)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to='account.individualownerprofile'),
        ),
        migrations.AddField(
            model_name='user',
            name='workspace_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['hotelprofile', 'guesthouseprofile', 'carlisting', 'eventspacelisting']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='user',
            name='workspace_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('company__isnull', False), ('individual_owner__isnull', False), models.Q(('company__isnull', True), ('individual_owner__isnull', True)), _connector='OR'), name='user_has_at_most_one_employer'),
        ),
    ]
