# Generated by Django 5.2.4 on 2026-02-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_add_hotel_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/logos/', verbose_name='Logo'),
        ),
    ]
