# Generated by Django 5.2.4 on 2026-06-06 07:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('password_change', 'Password Change')], default='login', max_length=32, verbose_name='Purpose')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Code Hash')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='Consumed At')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Attempts')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='Max Attempts')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'OTP Challenge',
                'verbose_name_plural': 'OTP Challenges',
                'db_table': 'otp_challenges',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone', 'purpose', 'created_at'], name='otp_challen_phone_8975d0_idx'), models.Index(fields=['user', 'purpose', 'consumed_at'], name='otp_challen_user_id_6aefa9_idx')],
            },
        ),
    ]
