# Generated by Django 5.2.4 on 2026-06-06 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_phone_verified_at_alter_otpchallenge_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the hotel has been verified by an administrator.', verbose_name='Is Verified'),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When the hotel was last verified by an administrator.', null=True, verbose_name='Verified At'),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who last verified this hotel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Verified By'),
        ),
    ]
