# Generated by Django 5.2.4 on 2026-06-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_hotelprofile_is_verified_hotelprofile_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the hotel is active and visible.', verbose_name='Is Active'),
        ),
    ]
