# Generated by Django 5.2.4 on 2026-06-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_hotelprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_change_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Phone Change Count'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_last_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Phone Last Changed At'),
        ),
    ]
