# Generated by Django 5.2.4 on 2026-06-11 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_user_phone_change_count_user_phone_last_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpchallenge',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('signup', 'Signup'), ('password_change', 'Password Change'), ('guest_hotel_booking', 'Guest Hotel Booking'), ('guest_guesthouse_booking', 'Guest Guesthouse Booking'), ('guest_eventspace_booking', 'Guest Event Space Booking'), ('guest_car_rental_booking', 'Guest Car Rental Booking')], default='login', max_length=32, verbose_name='Purpose'),
        ),
        migrations.AlterField(
            model_name='otpchallenge',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
