# Generated by Django 5.2.4 on 2026-06-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_otpchallenge_purpose_alter_otpchallenge_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='verification_note',
            field=models.CharField(blank=True, help_text='Optional note recorded by an administrator during verification.', max_length=500, null=True, verbose_name='Verification Note'),
        ),
    ]
