# Generated by Django 5.2.4 on 2026-06-11 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_hotelprofile_verification_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerComplianceAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('revoked', 'Revoked')], default='pending', max_length=20, verbose_name='Status')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Signed At')),
                ('agreement_version', models.CharField(max_length=50, verbose_name='Agreement Version')),
                ('note', models.TextField(blank=True, default='', verbose_name='Note')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compliance_agreements', to='account.individualownerprofile', verbose_name='Individual Owner')),
                ('signed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_owner_compliance_agreements', to=settings.AUTH_USER_MODEL, verbose_name='Signed By Admin')),
            ],
            options={
                'verbose_name': 'Owner Compliance Agreement',
                'verbose_name_plural': 'Owner Compliance Agreements',
                'db_table': 'owner_compliance_agreements',
                'ordering': ('-created_at',),
            },
        ),
    ]
