# Generated by Django 5.2.4 on 2026-06-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_ownercomplianceagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelprofile',
            name='address_components',
            field=models.JSONField(blank=True, null=True, verbose_name='Address Components'),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='formatted_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Formatted Address'),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='hotelprofile',
            name='place_id',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Place ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_known_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Last Known Latitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_known_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Last Known Longitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_permission_granted',
            field=models.BooleanField(default=False, verbose_name='Location Permission Granted'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Location Updated At'),
        ),
    ]
