# Generated by Django 5.2.4 on 2026-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_hotelprofile_address_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='split_config_active',
            field=models.BooleanField(default=False, help_text="Use this owner's split config when complete.", verbose_name='Split Config Active'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='split_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('flat', 'Flat')], help_text='Optional owner-specific platform commission split type.', max_length=20, null=True, verbose_name='Split Type'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='split_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Optional owner-specific platform commission value.', max_digits=12, null=True, verbose_name='Split Value'),
        ),
        migrations.AddField(
            model_name='individualownerprofile',
            name='split_config_active',
            field=models.BooleanField(default=False, help_text="Use this owner's split config when complete.", verbose_name='Split Config Active'),
        ),
        migrations.AddField(
            model_name='individualownerprofile',
            name='split_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('flat', 'Flat')], help_text='Optional owner-specific platform commission split type.', max_length=20, null=True, verbose_name='Split Type'),
        ),
        migrations.AddField(
            model_name='individualownerprofile',
            name='split_value',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Optional owner-specific platform commission value.', max_digits=12, null=True, verbose_name='Split Value'),
        ),
    ]
