# Generated by Django 5.2.4 on 2026-06-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_companyprofile_split_config_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpchallenge',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login'), ('signup', 'Signup'), ('password_change', 'Password Change'), ('guest_hotel_booking', 'Guest Hotel Booking'), ('guest_guesthouse_booking', 'Guest Guesthouse Booking'), ('guest_eventspace_booking', 'Guest Event Space Booking'), ('guest_car_rental_booking', 'Guest Car Rental Booking'), ('guest_car_sale_reveal', 'Guest Car Sale Reveal'), ('guest_property_sale_reveal', 'Guest Property Sale Reveal')], default='login', max_length=32, verbose_name='Purpose'),
        ),
    ]
