# Generated by Django 5.2.4 on 2026-06-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_add_property_rental_guest_otp_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownercomplianceagreement',
            name='agreement_document',
            field=models.FileField(blank=True, null=True, upload_to='owner_compliance_agreements/', verbose_name='Agreement Document'),
        ),
    ]
