"""
Django settings for marefiya project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
import dj_database_url
from environ import Env

# Celery Beat Schedule Configuration
from celery.schedules import crontab


env = Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY", cast=str)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=True, cast=bool)


# ALLOWED_HOSTS = env("ALLOWED_HOSTS").split(",")

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '0.0.0.0',
    '4a74b1285b13.ngrok-free.app',  # Specific ngrok subdomain
    '.ngrok-free.app',              # Allows all subdomains ending in .ngrok-free.app
    'michotmarefia.com',
    'www.michotmarefia.com',
    ]

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
# ]

# ! THIS SHOULD BE FOR DEV ONLY !!!
CORS_ALLOW_ALL_ORIGINS = True

WSGI_APPLICATION = "config.wsgi.application"

ROOT_URLCONF = "config.urls"

AUTH_USER_MODEL = "account.User"

DJANGO_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "drf_spectacular",
    "corsheaders",
]

CUSTOM_APPS = [
    "apps.account",
    "apps.core",
    "apps.listing",
    "apps.payment",
    "apps.analytics",
    "apps.favorites",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + CUSTOM_APPS

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {"default": dj_database_url.parse(env("DATABASE_URL"))}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

USE_I18N = True

TIME_ZONE = env("TIME_ZONE", cast=str, default="UTC")

USE_TZ = env("USE_TZ", cast=bool, default=True)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Include the project's top-level `static/` directory when collecting static files
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"

# DATALOOKUP_MODEL = "core.DataLookup"

# POLICIES_FILE_PATH = env(
#     "ACCESS_POLICY_FILE",
#     default=os.path.join(BASE_DIR, "config", "policies.json"),
#     cast=str,
# )

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "AUTH_TOKEN_CLASSES": ["rest_framework_simplejwt.tokens.AccessToken"],
    "ACCESS_TOKEN_LIFETIME": (timedelta(hours=1) if not DEBUG else timedelta(days=30)),
    "REFRESH_TOKEN_LIFETIME": (timedelta(days=1) if not DEBUG else timedelta(days=30)),
    "USER_ID_FIELD": "id",
    "ROTATE_REFRESH_TOKENS": True,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "",
    "DESCRIPTION": "Y",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}

JAZZMIN_SETTINGS = {
    "site_title": "Marefiya Admin",
    "site_header": "Michot Marefiya Admin",
    "site_brand": "Marefiya Panel",
    "welcome_sign": "Welcome to Michot Marefiya administration",
    "search_model": "account.User",
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "account": "fas fa-user",
        "listing": "fas fa-bed",
        "core": "fas fa-cog",
    },
    "site_logo": "img/michotmarefiyalogo.png",
    "site_logo_small": "img/michotmarefiyalogo.png",
    "site_icon": "img/michotmarefiyalogo.png",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "dark_mode": True,
    "sidebar_nav_small_text": False,
}

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
CSRF_TRUSTED_ORIGINS = ['https://michotmarefia.com', 'https://www.michotmarefia.com']


# config/settings/base.py (excerpt)
CHAPA_SECRET_KEY = env("CHAPA_SECRET_KEY", default=None)
CHAPA_WEBHOOK_SECRET = env("CHAPA_WEBHOOK_SECRET", default=None)
CHAPA_CALLBACK_URL = env("CHAPA_CALLBACK_URL", default=None)
FRONTEND_URL = env("FRONTEND_URL", default=None)
# --- Celery Configuration ---
# Use the Docker service name 'redis' as the hostname for the broker and backend.
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://redis:6379/0') 
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://redis:6379/0') 

# Timezone must match the Django TIME_ZONE
CELERY_TIMEZONE = TIME_ZONE 

# Configuration for task serialization
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
BOOKING_PENDING_TIMEOUT_MINUTES = 15


CELERY_BEAT_SCHEDULE = {
    "fetch-daily-exchange-rates-every-1-day": {
        "task": "apps.core.tasks.fetch_daily_exchange_rates",
        "schedule": crontab(hour=0, minute=5),  # Runs once a day at 12:05 AM
        "args": (),
    },
}
