# Generated by Django 5.2.4 on 2025-12-16 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDirtyDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('company_id', models.UUIDField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'analytics_dirty_dates',
                'unique_together': {('company_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CompanyDailyMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('company_id', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bookings_count', models.IntegerField(default=0)),
                ('confirmed_count', models.IntegerField(default=0)),
                ('cancelled_count', models.IntegerField(default=0)),
                ('avg_booking_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('top_listings', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_daily_metrics',
                'unique_together': {('company_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ListingDailyMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('listing_id', models.UUIDField(db_index=True)),
                ('company_id', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('bookings_count', models.IntegerField(default=0)),
                ('avg_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'db_table': 'listing_daily_metrics',
                'unique_together': {('listing_id', 'date')},
            },
        ),
    ]
