# Generated by Django 5.2.4 on 2025-12-08 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDirtyDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('company_id', models.UUIDField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'analytics_dirty_dates',
                'unique_together': {('company_id', 'date')},
            },
        ),
    ]
