# Generated by Django 5.2.4 on 2026-01-09 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('listing', '0012_alter_eventspacelisting_hotel'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='content_type',
            field=models.ForeignKey(blank=True, help_text='Type of booking (Booking, GuestHouseBooking, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='object_id',
            field=models.UUIDField(blank=True, help_text='ID of the booking object', null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Legacy field for hotel room bookings only - use booking_object instead', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='listing.booking'),
        ),
    ]
