# Generated by Django 5.2.4 on 2026-01-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymenttransaction_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='booking_type',
            field=models.CharField(choices=[('booking', 'Hotel Room'), ('guesthouse', 'Guesthouse'), ('eventspace', 'Event Space'), ('carrental', 'Car Rental')], default='booking', help_text='Discriminator for the type of booking', max_length=50),
        ),
    ]
