# Generated by Django 5.2.4 on 2026-02-04 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_company_user_individual_owner_and_more'),
        ('payment', '0003_paymenttransaction_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount taken as platform fee', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The rate used for this transaction (e.g. 0.05)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payout_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid (Split Success)'), ('failed', 'Failed (Split Error)'), ('na', 'Not Applicable')], default='pending', help_text='Status of the vendor payout split', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='vendor_company',
            field=models.ForeignKey(blank=True, help_text='Direct link to vendor company for ledger queries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='account.companyprofile'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='vendor_individual',
            field=models.ForeignKey(blank=True, help_text='Direct link to individual owner for ledger queries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='account.individualownerprofile'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='vendor_payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount sent to the vendor subaccount', max_digits=12, null=True),
        ),
    ]
