# Generated by Django 5.2.4

from django.db import migrations


def backfill_vendor_fields(apps, schema_editor):
    """
    Backfill vendor_company and vendor_individual fields for existing PaymentTransactions.
    Professional implementation using correct schema relationships.
    """
    PaymentTransaction = apps.get_model('payment', 'PaymentTransaction')
    Booking = apps.get_model('listing', 'Booking')
    GuestHouseBooking = apps.get_model('listing', 'GuestHouseBooking')
    EventSpaceBooking = apps.get_model('listing', 'EventSpaceBooking')
    CarRental = apps.get_model('listing', 'CarRental')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    # Get content types
    booking_ct = ContentType.objects.get_for_model(Booking)
    guesthouse_ct = ContentType.objects.get_for_model(GuestHouseBooking)
    eventspace_ct = ContentType.objects.get_for_model(EventSpaceBooking)
    carrental_ct = ContentType.objects.get_for_model(CarRental)
    
    updated_count = 0
    skipped_count = 0
    
    # Process each transaction type
    for tx in PaymentTransaction.objects.filter(vendor_company__isnull=True, vendor_individual__isnull=True):
        try:
            vendor_company = None
            vendor_individual = None
            
            # Hotel Bookings - HotelProfile has .company (OneToOne)
            if tx.content_type_id == booking_ct.id:
                booking = Booking.objects.select_related('items__room__hotel__company').filter(id=tx.object_id).first()
                if booking and booking.items.exists():
                    first_item = booking.items.first()
                    if first_item and first_item.room and first_item.room.hotel:
                        vendor_company = first_item.room.hotel.company
            
            # Guesthouse Bookings - GuestHouseProfile has .company OR .individual_owner
            elif tx.content_type_id == guesthouse_ct.id:
                # Use filter + first to properly resolve in migrations
                from apps.listing.models import GuestHouseBookingItem
                items = GuestHouseBookingItem.objects.filter(booking_id=tx.object_id).select_related(
                    'room__guest_house__company',
                    'room__guest_house__individual_owner'
                )
                if items.exists():
                    first_item = items[0]
                    if first_item.room and first_item.room.guest_house:
                        guest_house = first_item.room.guest_house
                        vendor_company = guest_house.company
                        vendor_individual = guest_house.individual_owner
            
            # Event Space Bookings -EventSpaceListing has .company OR .individual_owner
            elif tx.content_type_id == eventspace_ct.id:
                booking = EventSpaceBooking.objects.select_related(
                    'items__event_space__company',
                    'items__event_space__individual_owner'
                ).filter(id=tx.object_id).first()
                if booking and booking.items.exists():
                    first_item = booking.items.first()
                    if first_item and first_item.event_space:
                        event_space = first_item.event_space
                        vendor_company = event_space.company
                        vendor_individual = event_space.individual_owner
            
            # Car Rentals - CarListing has .company OR .individual_owner
            elif tx.content_type_id == carrental_ct.id:
                rental = CarRental.objects.select_related(
                    'rental_items__car_listing__company',
                    'rental_items__car_listing__individual_owner'
                ).filter(id=tx.object_id).first()
                if rental and rental.rental_items.exists():
                    first_item = rental.rental_items.first()
                    if first_item and first_item.car_listing:
                        car_listing = first_item.car_listing
                        vendor_company = car_listing.company
                        vendor_individual = car_listing.individual_owner
            
            # Save if we found vendor info
            if vendor_company or vendor_individual:
                tx.vendor_company = vendor_company
                tx.vendor_individual = vendor_individual
                tx.save(update_fields=['vendor_company', 'vendor_individual'])
                updated_count += 1
            else:
                skipped_count += 1
                        
        except Exception as e:
            # Log but continue processing
            print(f"Warning: Failed to backfill tx_ref={tx.tx_ref}: {e}")
            skipped_count += 1
            continue
    
    print(f"✅ Successfully backfilled {updated_count} transactions")
    if skipped_count > 0:
        print(f"⚠️  Skipped {skipped_count} transactions (could not resolve vendor)")


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymenttransaction_commission_amount_and_more'),
        ('listing', '0022_force_null_with_sql'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RunPython(backfill_vendor_fields, reverse_code=migrations.RunPython.noop),
    ]
