# Generated by Django 5.2.4 on 2026-06-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_backfill_vendor_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='booking_type',
            field=models.CharField(choices=[('booking', 'Hotel Room'), ('guesthouse', 'Guesthouse'), ('eventspace', 'Event Space'), ('carrental', 'Car Rental'), ('contact_reveal', 'Contact Reveal')], default='booking', help_text='Discriminator for the type of booking', max_length=50),
        ),
    ]
