# Generated by Django 5.2.4 on 2026-06-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_paymenttransaction_booking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax amount collected for eligible property rental transactions', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='tax_liability_status',
            field=models.CharField(blank=True, choices=[('applicable', 'Applicable'), ('not_applicable', 'Not Applicable')], help_text='Tax applicability status for this transaction', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tax rate used for eligible property rental transactions', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='booking_type',
            field=models.CharField(choices=[('booking', 'Hotel Room'), ('guesthouse', 'Guesthouse'), ('eventspace', 'Event Space'), ('carrental', 'Car Rental'), ('propertyrental', 'Property Rental'), ('contact_reveal', 'Contact Reveal')], default='booking', help_text='Discriminator for the type of booking', max_length=50),
        ),
    ]
