# Generated by Django 5.2.4 on 2026-06-12 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_paymenttransaction_tax_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='dispute_handled_by',
            field=models.ForeignKey(blank=True, help_text='Admin currently responsible for dispute triage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_payment_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='dispute_note',
            field=models.TextField(blank=True, help_text='Latest admin note for transaction dispute triage', null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='dispute_opened_at',
            field=models.DateTimeField(blank=True, help_text='When dispute triage was opened', null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='dispute_resolved_at',
            field=models.DateTimeField(blank=True, help_text='When dispute triage was resolved', null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='dispute_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('under_review', 'Under Review'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], help_text='Admin dispute triage status for this transaction', max_length=30, null=True),
        ),
    ]
