# Generated by Django 5.2.4 on 2026-06-14 15:40

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_paymenttransaction_dispute_handled_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlatformConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name', models.CharField(default='default', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_split_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat')], default='percentage', help_text='Default platform commission split type.', max_length=20)),
                ('default_split_value', models.DecimalField(decimal_places=4, default=Decimal('0.0200'), help_text='Default platform commission. For percentage, 0.02 means 2%.', max_digits=12)),
            ],
            options={
                'verbose_name': 'Payment Platform Config',
                'verbose_name_plural': 'Payment Platform Configs',
                'db_table': 'payment_platform_configs',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='one_active_payment_platform_config')],
            },
        ),
    ]
