# Generated by Django 5.2.4 on 2026-06-14 18:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_paymentplatformconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplatformconfig',
            name='default_car_sale_reveal_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Default contact reveal fee for car sale listings.', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentplatformconfig',
            name='default_property_sale_reveal_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Default contact reveal fee for property sale listings.', max_digits=10),
        ),
    ]
