# Generated by Django 5.2.4 on 2026-06-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_paymentplatformconfig_default_car_sale_reveal_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='booking_type',
            field=models.CharField(choices=[('booking', 'Hotel Room'), ('guesthouse', 'Guesthouse'), ('eventspace', 'Event Space'), ('carrental', 'Car Rental'), ('carrental_extension', 'Car Rental Extension'), ('propertyrental', 'Property Rental'), ('contact_reveal', 'Contact Reveal')], default='booking', help_text='Discriminator for the type of booking', max_length=50),
        ),
    ]
