# Generated by Django 5.2.4 on 2026-02-09 10:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('notification_type', models.CharField(max_length=50, unique=True, verbose_name='Notification Type')),
                ('title_template', models.CharField(max_length=255, verbose_name='Title Template')),
                ('message_template', models.TextField(verbose_name='Message Template')),
                ('email_subject_template', models.CharField(max_length=255, verbose_name='Email Subject Template')),
                ('email_body_template', models.TextField(verbose_name='Email Body Template (Text)')),
                ('email_html_template', models.TextField(blank=True, null=True, verbose_name='Email Body Template (HTML)')),
                ('required_variables', models.JSONField(blank=True, default=list, verbose_name='Required Variables')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('email_preferences', models.JSONField(blank=True, default=dict, verbose_name='Email Preferences')),
                ('in_app_preferences', models.JSONField(blank=True, default=dict, verbose_name='In-App Preferences')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Enable Email Notifications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('notification_type', models.CharField(choices=[('email_verified', 'Email Verified'), ('password_changed', 'Password Changed'), ('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('company_approved', 'Company Approved'), ('company_rejected', 'Company Rejected'), ('new_booking_received', 'New Booking Received'), ('payout_completed', 'Payout Completed'), ('new_company_registration', 'New Company Registration')], max_length=50, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('action_url', models.URLField(blank=True, null=True, verbose_name='Action URL')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read?')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('delivered_in_app', models.BooleanField(default=False, verbose_name='Delivered In-App')),
                ('delivered_email', models.BooleanField(default=False, verbose_name='Delivered Email')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email Sent At')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
