# Generated by Codex on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="delivered_push",
            field=models.BooleanField(default=False, verbose_name="Delivered Push"),
        ),
        migrations.AddField(
            model_name="notification",
            name="delivered_sms",
            field=models.BooleanField(default=False, verbose_name="Delivered SMS"),
        ),
        migrations.AddField(
            model_name="notification",
            name="push_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Push Sent At"),
        ),
        migrations.AddField(
            model_name="notification",
            name="sms_sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="SMS Sent At"),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="push_enabled",
            field=models.BooleanField(default=True, verbose_name="Enable Push Notifications"),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="push_preferences",
            field=models.JSONField(blank=True, default=dict, verbose_name="Push Preferences"),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="sms_enabled",
            field=models.BooleanField(default=False, verbose_name="Enable SMS Notifications"),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="sms_preferences",
            field=models.JSONField(blank=True, default=dict, verbose_name="SMS Preferences"),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="push_body_template",
            field=models.TextField(blank=True, verbose_name="Push Body Template"),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="push_title_template",
            field=models.CharField(blank=True, max_length=255, verbose_name="Push Title Template"),
        ),
        migrations.AddField(
            model_name="notificationtemplate",
            name="sms_template",
            field=models.CharField(blank=True, max_length=320, verbose_name="SMS Template"),
        ),
    ]
