# Generated by Django 5.2.4 on 2026-06-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_sms_push_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('email_verified', 'Email Verified'), ('password_changed', 'Password Changed'), ('booking_created', 'Booking Created'), ('booking_confirmed', 'Booking Confirmed'), ('booking_cancelled', 'Booking Cancelled'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('contact_reveal_unlocked', 'Contact Reveal Unlocked'), ('listing_deleted', 'Listing Deleted'), ('company_approved', 'Company Approved'), ('company_rejected', 'Company Rejected'), ('new_booking_received', 'New Booking Received'), ('payout_completed', 'Payout Completed'), ('new_company_registration', 'New Company Registration')], max_length=50, verbose_name='Type'),
        ),
    ]
